const data: Block[] = [
    {
        id: 1,
        type: 2,
        sequence: 0,
        style: null,
        title: '동영상 블록',
        subText01: null,
        subText02: null,
        url: 'https://youtu.be/HK4X8ckIJ-4?si=v-wnYRaYb6UbizW7',
        imgUrl: null,
        dateStart: null,
        dateEnd: null,
        openYn: 'Y',
        keepYn: 'N',
        dateCreate: '2024-10-11T12:26:44.000Z',
        dateUpdate: '2024-10-11T21:08:52.000Z',
        active: 1,
    },
    {
        id: 1,
        type: 1,
        sequence: 1,
        style: 1,
        title: '구분선 블록',
        subText01: null,
        subText02: null,
        url: null,
        imgUrl: null,
        dateStart: null,
        dateEnd: null,
        openYn: 'Y',
        keepYn: 'N',
        dateCreate: '2024-10-11T13:21:11.000Z',
        dateUpdate: '2024-10-11T17:50:36.000Z',
        active: 1,
    },
    {
        id: 1,
        type: 3,
        sequence: 4,
        style: 1,
        title: '링크 블록',
        subText01: null,
        subText02: null,
        url: 'https://www.naver.com',
        imgUrl: '',
        dateStart: null,
        dateEnd: null,
        openYn: 'Y',
        keepYn: 'N',
        dateCreate: '2024-10-11T19:58:46.000Z',
        dateUpdate: null,
        active: 1,
    },
    {
        id: 1,
        type: 4,
        sequence: 5,
        style: null,
        title: '이미지 블록',
        subText01: null,
        subText02: null,
        url: 'https://www.naver.com',
        imgUrl: '/assets/icons/icon_profile.png',
        dateStart: null,
        dateEnd: null,
        openYn: 'Y',
        keepYn: 'N',
        dateCreate: '2024-10-11T19:59:15.000Z',
        dateUpdate: null,
        active: 1,
    },
    {
        id: 1,
        type: 5,
        sequence: 6,
        style: null,
        title: '이벤트 블록',
        subText01: '서브 타이틀',
        subText02: '가이드라인',
        url: null,
        imgUrl: null,
        dateStart: '2024-10-01T21:26:44.000Z',
        dateEnd: '2024-10-31T21:26:44.000Z',
        openYn: 'Y',
        keepYn: 'N',
        dateCreate: '2024-10-11T20:08:27.000Z',
        dateUpdate: null,
        active: 1,
    },
    {
        id: 1,
        type: 6,
        sequence: 7,
        style: null,
        title: '텍스트 블록',
        subText01: null,
        subText02: null,
        url: null,
        imgUrl: null,
        dateStart: null,
        dateEnd: null,
        openYn: 'Y',
        keepYn: 'N',
        dateCreate: '2024-10-11T20:10:44.000Z',
        dateUpdate: null,
        active: 1,
    },
    {
        id: 1,
        type: 7,
        sequence: 8,
        style: 1,
        title: null,
        subText01: null,
        subText02: null,
        url: null,
        imgUrl: null,
        dateStart: null,
        dateEnd: null,
        openYn: 'Y',
        keepYn: 'N',
        dateCreate: '2024-10-11T20:39:15.000Z',
        dateUpdate: '2024-10-11T20:56:38.000Z',
        active: 1,
        schedule: [
            {
                id: 1,
                userId: 1,
                linkEditorId: 15,
                title: '일정 1',
                url: 'https://naver.com',
                dateStart: '2024-10-01T00:00:00.000Z',
                dateEnd: '2024-10-31T00:00:00.000Z',
                dateCreate: '2024-10-11T20:35:35.000Z',
                dateUpdate: '2024-10-11T20:56:38.000Z',
                active: 1,
            },
        ],
    },
];

export default data;
